---
- name: configuring httpd
  template:
    src: templates/index.j2
    dest: /var/www/html/index.html
- name: allowing traffic on firewall
  firewalld:
    service: http
    permanent: yes
    state: enabled
- name: reload firewall
  service:
    name: firewalld
    state: reloaded
...
